### ISSUE TITLE
Viewing received data

### ISSUE THREAD

**Issue by jeffreyclay** [PaddyCube/WirelessWeather#2]
I don't see anything mentioned regarding viewing or recording the data. Am I missing something?

**Comment by PaddyCube** [comment]
Hi, this weather station uses MQTT to send data. So it is up to you to install a MQTT broker where the station can send data to.

There is a newer Version using a Arduino Pro Mini and a 433 MHz Transmitter to send data. Also there is some example code where ESP8266 device acts as receiver and send data (again) using MQTT. As a MQTT target, you can also use something like Thingspeak.com
